/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package taxireservation.backend;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        assertThat(new App().getGreeting()).isNotNull();
    }
}
